# Generated by Django 3.2.9 on 2021-11-09 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('post_paragraph', models.TextField(blank=True, null=True)),
                ('post_description', models.TextField(blank=True, max_length=500, null=True)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
