# Generated by Django 3.2.9 on 2021-11-08 14:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('post_paragraph', models.TextField(blank=True, null=True)),
                ('post_description', models.TextField(blank=True, max_length=500, null=True)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('profle_id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile')),
            ],
        ),
    ]
