# Generated by Django 3.2.9 on 2021-11-09 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile', '0001_initial'),
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.userprofile'),
        ),
    ]
