# Generated by Django 3.2.9 on 2021-11-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profle_id_post',
            new_name='profile_id_post',
        ),
    ]
