# Generated by Django 3.2.9 on 2021-11-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_profile_id_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_id_post',
            new_name='profile_id',
        ),
    ]
