# Generated by Django 3.2.9 on 2021-11-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_alter_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_friend_id_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friend_id_one', to='User.user')),
                ('user_friend_id_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friend_id_two', to='User.user')),
            ],
        ),
    ]
