# Generated by Django 3.2.9 on 2021-11-09 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='user_friend_id_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friend_id_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friend',
            name='user_friend_id_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_friend_id_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
