# Generated by Django 3.2.9 on 2021-11-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Friend', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
