# Generated by Django 3.2.9 on 2021-11-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_userprofile_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
