# Generated by Django 3.2.9 on 2021-11-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
